app:
  port: ":8080"
  mode: "debug"
  log: "info"

database:
  username: "root"
  password: "123456"
  host: "localhost"
  port: 3306
  name: "test"

jwt:
  secret: a-string-secret-at-least-256-bits-long
  ttl: 24
